env:
  es2020: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:plugin:vue/vue3-recommended
parserOptions:
  ecmaVersion: latest
  parser: "@typescript-eslint/parser"
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  no-constant-condition: off
  "@typescript-eslint/no-explicit-any": off
ignorePatterns:
  - node_modules
  - dist
  - commitlint.config.js
