name: Drag and drop tests
on: [push, workflow_dispatch]
jobs:
  playwright:
    name: "Playwright tests"
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install --frozen-lockfile
      - name: Build Nuxt
        run: cd playground && pnpm install && cd ..
      - name: Install Playwright
        run: pnpm exec playwright install --with-deps
      - name: Spin up dev
        run: pnpm playground &
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
